name: release

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Generate tag
        id: tag
        run: |
          git tag -d v-1753777640
          git push origin :refs/tags/v-1753777640

      - name: Create tag
        run: |
          git tag v1.0.0  # 这里的 v1.0.0 可以根据实际情况修改
          git push origin v1.0.0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}