name: release

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      -
        name: Create and push tag
        run: |
          DATE=$(date +%Y%m%d)
          TAG_NAME="v${DATE}"
          git tag -d $TAG_NAME || true
          git push origin :refs/tags/$TAG_NAME || true
          # 创建标签
          git tag $TAG_NAME
          # 推送标签到远程仓库
          git push origin $TAG_NAME
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}